name: Dev pipeline

on:
  push:
    branches:
      - develop

env:
  BUILD_VERSION_OFFSET: 10

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 11 }

      - name: Calculate build version
        id: param
        env:
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          echo "BUILD_VERSION=${{ $BUILD_NUMBER + $BUILD_VERSION_OFFSET }}" >> $GITHUB_ENV

      - name: Bump version code
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{steps.param.BUILD_VERSION}}

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Create google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -di > /home/runner/work/pets/pets/app/google-services.json

      - name: Build release AAB
        run: ./gradlew bundleRelease

      - name: Uploading build to IAS
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.GOOGLE_SERVICE_ACCOUNT_JSON}}
          packageName: by.dro.pets
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internalsharing

      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Repository: ${{ github.repository }}
            Build version: ${{github.run_number}}

            ${{ env.INTERNAL_SHARING_DOWNLOAD_URL }}
