name: Prod pipeline

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Building release app
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 11}
        
      - name: Bump version code
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{github.run_number}}
        
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Create file google-services.json
        run: cat /home/runner/work/pets/pets/app/google-services.json | base64
        
      - name: Putting data google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/pets/pets/app/google-services.json
        
      - name: Build APK and AAB
        run: |
         ./gradlew bundleRelease
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: |
            app/build/outputs/bundle/release/app-release.aab
            app/build/outputs/mapping/release/mapping.txt
          
  upload_to_test_track:
      name: Uploading to Internal test
      needs: build
      runs-on: ubuntu-latest
      steps:
      
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: bundle
          
      - name: Sign Release AAB
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        
      - name: Uploading to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.GOOGLE_SERVICE_ACCOUNT_JSON}}
          packageName: by.dro.pets
          releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
          status: completed
          track: internal
          mappingFile: mapping/release/mapping.txt
          
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          #document: apk/release/app-release-unsigned.apk
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            Build version: ${{github.run_number}}
            
            Build in Google Play Internal Test!
